name: Render library update
on:
  schedule:
  - cron: "05 17 * * 1-5"
    branches: main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run:
          Rscript -e "install.packages(c('tidyverse', 'janitor', 'zoo', 'httr', 'openxlsx', 'ISOweek', 'CSOdata', 'openxlsx'))"
      - name: Render r plot file
        run:
          Rscript -e "source('fordiarmuid.R')"
      - name: Commit results
        run: |
          git add -A
          git commit -m ' data updated!' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
